from enum import Enum


class EventType(str, Enum):
    KICKOFF = "KICKOFF"
    HALF_TIME = "HALF_TIME"
    FULL_TIME = "FULL_TIME"

    GOAL = "GOAL"
    OWN_GOAL = "OWN_GOAL"

    SHOT = "SHOT"
    SHOT_ON_TARGET = "SHOT_ON_TARGET"
    SAVE = "SAVE"

    PASS = "PASS"
    THROUGH_BALL = "THROUGH_BALL"
    CROSS = "CROSS"

    CORNER = "CORNER"
    THROW_IN = "THROW_IN"
    GOAL_KICK = "GOAL_KICK"

    FOUL = "FOUL"
    OFFSIDE = "OFFSIDE"

    YELLOW_CARD = "YELLOW_CARD"
    RED_CARD = "RED_CARD"
    SECOND_YELLOW = "SECOND_YELLOW"

    SUBSTITUTION = "SUBSTITUTION"

    PENALTY = "PENALTY"
    MISSED_PENALTY = "MISSED_PENALTY"

    VAR_CHECK = "VAR_CHECK"
    VAR_DECISION = "VAR_DECISION"

    INJURY = "INJURY"