"""Initial schema

Revision ID: 95dff722de3e
Revises: 
Create Date: 2026-07-01 09:10:45.113837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95dff722de3e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitions',
    sa.Column('competition_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('competition_name', sa.String(length=100), nullable=False),
    sa.Column('competition_type', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('organizer', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('competition_id')
    )
    op.create_table('players',
    sa.Column('player_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('nationality', sa.String(length=100), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('preferred_foot', sa.String(length=10), nullable=False),
    sa.Column('profile_image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('teams',
    sa.Column('team_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_name', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.Column('fifa_team_code', sa.String(length=10), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('confederation', sa.String(length=50), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('flag_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('team_id'),
    sa.UniqueConstraint('fifa_team_code')
    )
    op.create_table('venues',
    sa.Column('venue_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stadium_name', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('venue_id')
    )
    op.create_table('player_teams',
    sa.Column('player_team_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('jersey_number', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('player_team_id')
    )
    op.create_table('seasons',
    sa.Column('season_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('season_name', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.competition_id'], ),
    sa.PrimaryKeyConstraint('season_id')
    )
    op.create_table('matches',
    sa.Column('match_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('kickoff_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('attendance', sa.Integer(), nullable=True),
    sa.Column('referee', sa.String(), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=False),
    sa.Column('away_score', sa.Integer(), nullable=False),
    sa.Column('winner', sa.String(), nullable=True),
    sa.Column('went_to_extra_time', sa.Boolean(), nullable=False),
    sa.Column('went_to_penalties', sa.Boolean(), nullable=False),
    sa.Column('home_penalty_score', sa.Integer(), nullable=True),
    sa.Column('away_penalty_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.team_id'], ),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.competition_id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.team_id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.season_id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.venue_id'], ),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_table('timeline_events',
    sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('related_player_id', sa.Integer(), nullable=True),
    sa.Column('minute', sa.Integer(), nullable=False),
    sa.Column('second', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('event_type', sa.Enum('KICKOFF', 'HALF_TIME', 'FULL_TIME', 'GOAL', 'OWN_GOAL', 'SHOT', 'SHOT_ON_TARGET', 'SAVE', 'PASS', 'THROUGH_BALL', 'CROSS', 'CORNER', 'THROW_IN', 'GOAL_KICK', 'FOUL', 'OFFSIDE', 'YELLOW_CARD', 'RED_CARD', 'SECOND_YELLOW', 'SUBSTITUTION', 'PENALTY', 'MISSED_PENALTY', 'VAR_CHECK', 'VAR_DECISION', 'INJURY', name='eventtype'), nullable=False),
    sa.Column('event_subtype', sa.String(length=50), nullable=True),
    sa.Column('outcome', sa.String(length=50), nullable=True),
    sa.Column('x_coordinate', sa.Float(), nullable=True),
    sa.Column('y_coordinate', sa.Float(), nullable=True),
    sa.Column('short_description', sa.String(length=255), nullable=True),
    sa.Column('detailed_description', sa.String(length=1000), nullable=True),
    sa.Column('provider_event_id', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('importance_score', sa.Float(), nullable=True),
    sa.Column('sentiment_shift', sa.Float(), nullable=True),
    sa.Column('raw_reference', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['related_player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timeline_events')
    op.drop_table('matches')
    op.drop_table('seasons')
    op.drop_table('player_teams')
    op.drop_table('venues')
    op.drop_table('teams')
    op.drop_table('players')
    op.drop_table('competitions')
    # ### end Alembic commands ###
